# Welcome to Jekyll!
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: en-US
title: "The Thinking Forest"
description: "A place to relax and think about life"
baseurl: ""
url: "https://ThinkingForest.org"
logo: "/assets/images/LYD-Cover.jpg"
timezone: Asia/Seoul
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
#mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Roboto"
    weights: "400,400i,700,700i"
  - name: "Roboto Slab"
    weights: "400,400i,700,700i"
#google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
#disqus:
#  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: "ThinkingForest"

# Liquid
liquid:
  error_mode: strict

# Build settings
#permalink: /:year/:title/
permalink: /:slug/
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search: true
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - github-pages
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-search

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: "Joshua. I. James"
  picture: "https://thinkingforest.org/assets/images/JoshuaProfile.jpg"
  email: "hvva+ThinkingForest@pm.me"
  twitter: "https://twitter.com/ThinkingForest"
  links:
    - title: "[Book] Living your dreams"
      url: "https://amzn.to/37QEZ2Y"
      icon: fab fa-amazon

# Footer Links
footer_links:
  - title: Dreams
    url: https://amzn.to/37QEZ2Y
    icon: fab fa-amazon
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

copyright: "Copyright 2019-2020 Joshua I. James. All rights reserved."